#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage: $0 --resource=<file> --cidfile=<filename> <command-file>"
    exit 0
fi

docker_host=$(cat $1 | jq '.result.endpoint')
cidfile=$2

env DOCKER_HOST="$docker_host" executor --cidfile=$2 "$3"
