#!/usr/bin/env ruby
require 'optparse'

if $0 == __FILE__
  opt = OptionParser.new
  opt.banner = "Usage: #{$0} [options] <command-file>"
  opt.parse!(ARGV)

  unless ARGV.length == 1
    puts opt.help
    exit
  end

  command_file = ARGV.first
  unless File.exist?(command_file)
    raise "No such file: #{command_file}"
  end

  cmd = open(command_file).readlines.join
  cmd = insert_cidarg(cmd)
  system(cmd)
  exit $?.exitstatus
end

def insert_cidarg(cmd)
  state_dir=ENV['STATE_DIR']
  cmd.sub('--rm', "--cidfile=#{state_dir}/cid")
end
