#!/usr/bin/env ruby
require 'optparse'

def insert_arg(cmd, name, cidfile)
  replaced = []
  replaced << "--name=#{name}" unless name.nil?
  replaced << "--cidfile=#{cidfile}" unless cidfile.nil?
  cmd.sub('--rm', replaced.join(' '))
end

if $0 == __FILE__
  opt = OptionParser.new
  opt.banner = "Usage: #{$0} [options] <command-file>"
  cidfile = nil
  name = nil
  opt.on('--cidfile=[FILE]') { |cid|
    cidfile = cid
  }
  opt.on('--name=NAME') { |n|
    name = n
  }
  opt.parse!(ARGV)

  unless ARGV.length == 1
    puts opt.help
    exit
  end

  command_file = ARGV.first
  unless File.exist?(command_file)
    raise "No such file: #{command_file}"
  end

  cmd = open(command_file).readlines.join
  unless cidfile.nil? and name.nil?
    cmd = insert_arg(cmd, name, cidfile)
  end
  system(cmd)
  exit $?.exitstatus
end
