version: "3.7"
services:
  dind:
    image: docker:stable-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    working_dir: /workspace/ep3
    volumes:
      - ..:/workspace/ep3
      - /tmp:/tmp
    command: dockerd-entrypoint.sh
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   USER_UID: $UID
      #   USER_GID: $UID
    environment:
      DOCKER_HOST: tcp://dind:2375/
      ES_HOST: es
      ES_PORT: $ES_PORT
    working_dir: /workspace/ep3
    volumes:
      - ..:/workspace/ep3
      - /tmp:/tmp
    command: sleep infinity
    depends_on:
      - "dind"
      - "es"
  es:
    image: elasticsearch:7.7.0
    ports:
      - ${ES_PORT}:9200
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "cwl-metrics-passwd"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=warning:stderr:utctime"
      TAKE_FILE_OWNERSHIP: "true"
