version: "3.7"
services:
  dind:
    image: docker:stable-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    working_dir: /workspace/ep3
    volumes:
      - ..:/workspace/ep3
      - /tmp:/tmp
    command: dockerd-entrypoint.sh
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${UID}
        - USER_GID=${UID}
    environment:
      DOCKER_HOST: tcp://dind:2375/
    working_dir: /workspace/ep3
    volumes:
      - ..:/workspace/ep3
      - /tmp:/tmp
    command: sleep infinity
    depends_on:
      - "dind"
  # elasticsearch:
  #   image: elasticsearch:7.7.0
  #   container_name: cwl-metrics-elasticsearch
  #   ports:
  #     - 9200:9200
  #   environment:
  #     bootstrap.memory_lock: "true"
  #     discovery.type: "single-node"
  #     ELASTIC_PASSWORD: "cwl-metrics-passwd"
  #     ES_JAVA_OPTS: "-Xms1g -Xmx16g -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=warning:stderr:utctime"
  #     TAKE_FILE_OWNERSHIP: "true"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   restart: always
